### PR TITLE
WIP Admin panel form errors

### LINKED ISSUE #121: Admin panel forms need to display submission errors
Similar to the feature implemented in #117

### PR DESCRIPTION
**Pull request by APM246**
image

Closes #121 

## Proposed Changes
  - Similar to #117, error states for the admin panel forms are long overdue
  - Changes phone length to 15 chars in User table
 
If you're fine with this idea I'll add it to the other forms such as adding carparks, editing users, editing bookings, etc.

### CODE REVIEW

**Review by zollf — APPROVED** [review]

**Comment by APM246** [comment]
Should I proceed to add this to the other forms (through storing error messages within session objs)?

**Comment by zollf** [comment]
> Should I proceed to add this to the other forms (through storing error messages within session objs)?

yes please

**Comment by zollf** [comment]
you need to resolve conflicts correctly otherwise they get pushed into the commit.

**Comment by zollf** [comment]
Best idea is revert and then try merging again. Make sure you run tests/lints before u commit, as they will pick up conflict syntax. Also if youre using command line to commit you need to be extra careful

**Comment by APM246** [comment]
Idk I never used to have issues with fixing merge conflicts. My VS Code is acting funky

**Comment by APM246** [comment]
Going to force remove last 5 commits from remote

**Comment by APM246** [comment]
Commit also changes phone length in User model to 15 chars

**Comment by APM246** [comment]
Does it let you re-approve the PR? I'm not sure if you've reviewed it

**Comment by zollf** [comment]
> Does it let you re-approve the PR? I'm not sure if you've reviewed it

Looks good, merge whenever

**Pull request merged**
